using System.Collections.Generic;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Jellyfin.Plugin.TwoFactorAuth.Services;

/// <summary>
/// Renders the freshly-generated recovery codes as a single-page A4 PDF the
/// user can print and stash. Codes are generation-time only — once dismissed
/// the server has no way to re-derive them, so this PDF is the user's last
/// chance to capture the plaintext.
///
/// QuestPDF community license is free for projects under USD 1M revenue —
/// applies to a self-hosted OSS plugin. License blurb is required in
/// distribution; included in README.
/// </summary>
public class RecoveryCodePdfService
{
    static RecoveryCodePdfService()
    {
        // Required once per process — license must be set before first render.
        // Community license is free for projects with < $1M revenue.
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] Render(string username, IReadOnlyList<string> codes, string serverName)
    {
        var generated = System.DateTime.UtcNow.ToString("u");
        var doc = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(t => t.FontSize(11).FontFamily(Fonts.SegoeUI));

                page.Header().Column(col =>
                {
                    col.Item().Text(serverName).FontSize(20).Bold();
                    col.Item().Text($"Two-Factor Authentication — recovery codes for {username}")
                        .FontSize(13).FontColor(Colors.Grey.Darken1);
                    col.Item().PaddingTop(2).Text($"Generated {generated} UTC")
                        .FontSize(9).FontColor(Colors.Grey.Darken1);
                });

                page.Content().PaddingVertical(15).Column(col =>
                {
                    col.Item().PaddingBottom(10).Text(t =>
                    {
                        t.Span("KEEP THESE SECRET. ").Bold();
                        t.Span("Each code works ONCE. Use them to sign in if you lose access to your authenticator app.");
                    });

                    col.Item().Border(1).BorderColor(Colors.Grey.Lighten1).Padding(15).Column(box =>
                    {
                        var width = 3;
                        box.Item().Table(tab =>
                        {
                            tab.ColumnsDefinition(c =>
                            {
                                for (var i = 0; i < width; i++) c.RelativeColumn();
                            });
                            for (var i = 0; i < codes.Count; i++)
                            {
                                tab.Cell().PaddingVertical(6).Text($"{i + 1:D2}.  {codes[i]}")
                                    .FontFamily(Fonts.Consolas).FontSize(13);
                            }
                        });
                    });

                    col.Item().PaddingTop(20).Text(
                        "If you ever lose all of your recovery codes AND your authenticator, " +
                        "an admin must reset your 2FA from the server's admin panel.")
                        .FontSize(9).FontColor(Colors.Grey.Darken1);
                });

                page.Footer().AlignCenter().Text("Generated by Jellyfin Two-Factor Authentication plugin")
                    .FontSize(8).FontColor(Colors.Grey.Lighten1);
            });
        });

        return doc.GeneratePdf();
    }
}
